version: '3'

services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - network_inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - network_inception
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    restart: on-failure
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - network_inception
    env_file: ./.env
    ports:
      - "443:443"

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/phbarrad/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'home/phbarrad/data/mariadb'

networks:
  network_inception:
    driver: bridge
